# This rule is not used by the project go-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over scaling.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: go-operator
    app.kubernetes.io/managed-by: kustomize
  name: scalingrule-admin-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - scalingrules
  verbs:
  - '*'
- apiGroups:
  - scaling.example.com
  resources:
  - scalingrules/status
  verbs:
  - get
